### PR TITLE
Improving handling of execution contexts

### PR DESCRIPTION
**Pull request by Sam-Burns**

### CODE REVIEW

**Comment by Sam-Burns** [comment]
Any news on this? Is the project abandoned?

**Comment by maxbaldanza** [comment]
@Sam-Burns this looks very useful. Care to re-open and we'll get that added 👍

**Comment by Sam-Burns** [comment]
@maxbaldanza wilco

**Comment by Sam-Burns** [comment]
@maxbaldanza Reopened at https://github.com/MageTest/MageSpec/pull/150.

**Pull request closed without merging**
